#! /bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
picom &
feh --bg-fill $HOME/.local/share/wallpapers/pinksky.jpeg &
~/.config/polybar/launch.sh

# Workspaces
bspc monitor -d I II III IV V

# Other
bspc config border_radius	16
bspc config border_width	0
bspc config window_gap		13
bspc config split_ratio		0.5
